export const constants = {
    title: 'Форма регистрации',
    successSubmit: 'Успешно зарегистрировано',
    requiredInput: 'Поле обязательно для заполнения',
    error: 'Error!',
    correctMail: 'Введите корректный email',
    passwordSymbolAmount: 'Пароль должен содержать 6 и более символов',
    passwordCapitalLetter: 'Пароль должен содержать хотя бы одну заглавную букву',
    passwordMismatch: 'Пароли не совпадают',
    chooseCorrectDate: 'Выберите корректную дату рождения',
    namePlaceholder: 'Имя пользователя',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Пароль',
    passwordConfirmationPlaceholder: 'Подтверждение пароля',
    phoneNumberPlaceholder: 'Номер телефона',
    datePlaceholder: 'Дата рождения',
    female: 'Женский',
    male: 'Мужской',
    registrationButton: 'Зарегистрироваться',
    labelName: 'Имя пользователя:',
    labelEmail: 'Email:',
    passwordLabel: 'Пароль:',
    passwordConfirmLabel: 'Подтверждение пароля:',
    phoneNumberLabel: 'Номер телефона:',
    dateLabel: 'Дата рождения:',
    genderLabel: 'Пол:',
};
